# Generated by Django 3.0.10 on 2020-10-09 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Importstep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('randomkey', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=80)),
                ('department', models.CharField(max_length=80)),
                ('building', models.CharField(max_length=80)),
                ('room', models.CharField(max_length=80)),
                ('seat_min', models.IntegerField()),
                ('seat_max', models.IntegerField()),
                ('importstep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='room.Importstep')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('hash', models.CharField(db_index=True, max_length=80, unique=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='room.Room')),
            ],
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('organization', 'department', 'building', 'room'), name='orgdeptbldgroomunique_room'),
        ),
    ]
