# Generated by Django 3.0.10 on 2020-10-12 16:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('givenname', models.CharField(help_text='Rufname / the firstname by which you are commonly known', max_length=80, verbose_name='Vorname / Given name')),
                ('familyname', models.CharField(help_text='Wie im Ausweis angegeben / as shown in your passport', max_length=80, verbose_name='Familienname / Family name')),
                ('street_and_number', models.CharField(max_length=80, verbose_name='Straße und Hausnummer / Street and number')),
                ('zipcode', models.CharField(max_length=80, validators=[django.core.validators.RegexValidator(message='5 Ziffern bitte / 5 digits, please', regex='^\\d{5}$')], verbose_name='Postleitzahl / Postal code')),
                ('town', models.CharField(max_length=80, verbose_name='Ort / Town')),
                ('phone', models.CharField(help_text="Mit Ländervorwahl, z.B. +49 151 ... in Deutschland / With country code, starting with '+'", max_length=80, validators=[django.core.validators.RegexValidator(message='Falsches Format für eine TelefonnummerWrong format as a phone number', regex='^\\+\\d\\d[\\d /-]+$')], verbose_name='Mobilfunknummer / Mobile phone number')),
                ('email', models.EmailField(help_text='Bitte immer die gleiche benutzen! / Please use the same one each time', max_length=80, verbose_name='Emailadresse / Email address')),
                ('present_from_dt', models.DateTimeField(max_length=80)),
                ('present_to_dt', models.DateTimeField(max_length=80)),
                ('submission_dt', models.DateTimeField(auto_now_add=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='room.Seat')),
            ],
        ),
    ]
