# Generated by Django 3.0.10 on 2020-10-15 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='cookie',
            field=models.TextField(default='abc', max_length=15, verbose_name='random string, used as pseudo-id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='room',
            name='department',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='room',
            name='organization',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='room',
            name='room',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='visit',
            name='email',
            field=models.EmailField(db_index=True, help_text='Bitte immer die gleiche benutzen! / Please use the same one each time', max_length=80, verbose_name='Emailadresse / Email address'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='familyname',
            field=models.CharField(db_index=True, help_text='Wie im Ausweis angegeben / as shown in your passport', max_length=80, verbose_name='Familienname / Family name'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='givenname',
            field=models.CharField(db_index=True, help_text='Rufname / the firstname by which you are commonly known', max_length=80, verbose_name='Vorname / Given name'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='phone',
            field=models.CharField(db_index=True, help_text="Mit Ländervorwahl, z.B. +49 151... in Deutschland / With country code, starting with '+'", max_length=80, validators=[django.core.validators.RegexValidator(message='Falsches Format für eine Telefonnummer / Wrong format as a phone number', regex='^\\+\\d\\d[\\d /-]+$')], verbose_name='Mobilfunknummer / Mobile phone number'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='present_from_dt',
            field=models.DateTimeField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='visit',
            name='present_to_dt',
            field=models.DateTimeField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='visit',
            name='street_and_number',
            field=models.CharField(db_index=True, help_text="Wohnadresse für diese Woche / This week's living address", max_length=80, verbose_name='Straße und Hausnummer / Street and number'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='town',
            field=models.CharField(db_index=True, max_length=80, verbose_name='Ort / Town'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='zipcode',
            field=models.CharField(db_index=True, max_length=80, validators=[django.core.validators.RegexValidator(message='5 Ziffern bitte / 5 digits, please', regex='^\\d{5}$')], verbose_name='Postleitzahl / Postal code'),
        ),
    ]
