# Generated by Django 3.0.10 on 2020-10-22 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0003_add_visit_cookie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importstep',
            name='randomkey',
        ),
        migrations.AddField(
            model_name='importstep',
            name='num_existing_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importstep',
            name='num_existing_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importstep',
            name='num_new_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importstep',
            name='num_new_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importstep',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
