# Generated by Django 3.0.10 on 2020-12-30 11:36

import anwesende.utils.validators
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_extend_importstep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='number',
            new_name='seatnumber',
        ),
        migrations.AlterField(
            model_name='visit',
            name='familyname',
            field=models.CharField(db_index=True, help_text='Wie im Ausweis angegeben / as shown in your passport (Latin script)', max_length=80, validators=[anwesende.utils.validators.validate_isprintable], verbose_name='Familienname / Family name'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='givenname',
            field=models.CharField(db_index=True, help_text='Rufname / the firstname by which you are commonly known', max_length=80, validators=[anwesende.utils.validators.validate_isprintable], verbose_name='Vorname / Given name'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='phone',
            field=models.CharField(db_index=True, help_text="Mit Ländervorwahl, z.B. +49 151... in Deutschland / With country code, starting with '+'", max_length=80, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['ASCII'], message='Falsches Format für eine Telefonnummer / Wrong format as a phone number', regex='^\\+\\d\\d[\\d /-]+$')], verbose_name='Mobilfunknummer / Mobile phone number'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='street_and_number',
            field=models.CharField(db_index=True, help_text="Wohnadresse für diese Woche / This week's living address", max_length=80, validators=[anwesende.utils.validators.validate_isprintable], verbose_name='Straße und Hausnummer / Street and number'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='town',
            field=models.CharField(db_index=True, max_length=80, validators=[anwesende.utils.validators.validate_isprintable], verbose_name='Ort / Town'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='zipcode',
            field=models.CharField(db_index=True, max_length=80, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['ASCII'], message='5 Ziffern bitte / 5 digits, please', regex='^\\d{5}$')], verbose_name='Postleitzahl / Postal code'),
        ),
    ]
