# Generated by Django 3.0.10 on 2020-12-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_number_to_seatnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='rownumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
