# Generated by Django 3.0.10 on 2021-01-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_seat_rownumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='seat_max',
        ),
        migrations.RemoveField(
            model_name='room',
            name='seat_min',
        ),
        migrations.AddField(
            model_name='room',
            name='seat_last',
            field=models.CharField(default='r1s1', help_text="e.g. 'r2s7' for row 2, seat 7 (14 seats total in the room)", max_length=80),
            preserve_default=False,
        ),
    ]
