# Generated by Django 3.0.10 on 2021-04-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_seat_min_and_max_become_seat_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Bitte immer die gleiche benutzen! / Please use the same one each time', max_length=80, verbose_name='Emailadresse / Email address'),
        ),
    ]
