# Generated by Django 3.0.10 on 2021-07-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_visit_email_can_be_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='row_dist',
            field=models.FloatField(default=1.4, help_text='smallest distance between people in two adjacent rows in meters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='seat_dist',
            field=models.FloatField(default=1.4, help_text='smallest distance between people in two adjacent seats in meters'),
            preserve_default=False,
        ),
    ]
