# Generated by Django 3.0.10 on 2021-09-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_row_and_seat_dist'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='status_3g',
            field=models.IntegerField(choices=[(22, 'vollständig geimpft / fully vaccinated'), (24, 'genesen / recovered'), (26, 'getestet / tested'), (87, 'weder noch / none of the above'), (88, 'unbekannt')], default=88, help_text="Siehe <a href='https://www.gesetze-im-internet.de/schausnahmv/__2.html'>die Verordnung</a> / (see regulation, in german only)", verbose_name='3G-Status gemäß §2 SchAusnahmV'),
        ),
    ]
