# Generated by Django 3.2.8 on 2021-11-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_visit_status_3g'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='descriptor',
            field=models.CharField(default='', help_text="a materialization: 'organization;department;building;room' for search", max_length=320),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='status_3g',
            field=models.IntegerField(choices=[(22, 'vollständig geimpft / fully vaccinated'), (24, 'genesen / recovered'), (26, 'getestet / tested'), (87, 'weder noch / none of the above'), (88, 'unbekannt')], default=88, help_text="Siehe <a href='https://www.gesetze-im-internet.de/schausnahmv/__2.html'>die Verordnung</a> / (see regulation, in german only)", verbose_name='3G-Status gemäß §2 SchAusnahmV / vaccination status'),
        ),
    ]
