# Generated by Django 3.2.8 on 2021-11-12 16:35

from django.db import migrations


def compute_room_descriptor(apps, schema_editor):
    Room = apps.get_model('room', 'Room')
    for room in Room.objects.all():
        # must agree with Room.save():
        room.descriptor = "%s;%s;%s;%s" % (
            room.organization, room.department, room.building, room.room)
        room.save()


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_room_descriptor'),
    ]

    operations = [
        migrations.RunPython(compute_room_descriptor),  # no backward migration is needed
    ]
