#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py collectstatic --noinput
python /app/manage.py migrate
python /app/manage.py make_base_data

/usr/local/bin/gunicorn config.wsgi \
    --worker-class gthread \
    --workers $GUNICORN_WORKERS \
    --threads $GUNICORN_THREADS \
    --max-requests 1000 \
    --max-requests-jitter 111 \
    --bind 0.0.0.0:5000 \
    --chdir=/app
