#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py collectstatic --noinput
python /app/manage.py migrate
python /app/manage.py make_base_data

/usr/local/bin/gunicorn config.wsgi \
    --workers 5 \
    --threads 4 \
    --bind 0.0.0.0:5000 \
    --chdir=/app
