#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput
python /app/manage.py migrate
python /app/manage.py ensure_datenverwalter_group

/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
